ALTER PROCEDURE AFF_POLICYCOMMISION_GetList_AdminWeb
    @KEYWORD NVARCHAR(500) = '',
    @ISACTIVE INT = 1,
    @ISDELETED INT = 0,
    @AFFILIATETYPEID BIGINT = NULL,
    @PAGEINDEX INT = 1,
    @PAGESIZE INT = 25
AS 
BEGIN

    SELECT 
            AFF_POLICYCOMMISION.POLICYCOMMISIONID,
            AFF_POLICYCOMMISION.POLICYCOMMISIONNAME,
            AFF_POLICYCOMMISION.AFFILIATETYPEID,
            AFF_POLICYCOMMISION.ISACTIVE,
            AFF_POLICYCOMMISION.ISLIMITEDTIME,
            AFF_POLICYCOMMISION.ISDEFAULT,
            IIF(AFF_POLICYCOMMISION.STARTDATEREGISTER IS NOT NULL, FORMAT(AFF_POLICYCOMMISION.STARTDATEREGISTER, 'dd/MM/yyyy') , '') STARTDATEREGISTERVIEW,
            IIF(AFF_POLICYCOMMISION.ENDDATEREGISTER IS NOT NULL, FORMAT(AFF_POLICYCOMMISION.ENDDATEREGISTER, 'dd/MM/yyyy') , '') ENDDATEREGISTERVIEW,
            AFF_AFFILIATETYPE.AFFILIATETYPENAME,
            COUNT(1) OVER() AS TOTALITEMS
    FROM    AFF_POLICYCOMMISION

    JOIN    AFF_AFFILIATETYPE
    ON      AFF_POLICYCOMMISION.AFFILIATETYPEID = AFF_AFFILIATETYPE.AFFILIATETYPEID
    AND     AFF_AFFILIATETYPE.ISACTIVE = 1
    AND     AFF_AFFILIATETYPE.ISDELETED = 0

    WHERE   (@ISACTIVE = 2 OR AFF_POLICYCOMMISION.ISACTIVE = @ISACTIVE)
    AND     (@ISDELETED = 2 OR AFF_POLICYCOMMISION.ISDELETED = @ISDELETED)
    AND     (
                @KEYWORD IS NULL
                OR @KEYWORD = ''
                OR AFF_POLICYCOMMISION.POLICYCOMMISIONNAME like '%'+@KEYWORD+'%'  collate Latin1_General_CI_AI_WS
            )
    AND     (@AFFILIATETYPEID IS NULL OR AFF_POLICYCOMMISION.AFFILIATETYPEID = @AFFILIATETYPEID)

    ORDER BY AFF_POLICYCOMMISION.CREATEDDATE DESC 
    OFFSET      (@PAGEINDEX -1)* @PAGESIZE ROWS
	FETCH NEXT  @PAGESIZE ROWS ONLY

END