CREATE PROCEDURE AFF_AFFILIATE_GetOption_AdminWeb
AS 
BEGIN

    SELECT  AFF_AFFILIATETYPE.AFFILIATETYPEID AS value,
            AFF_AFFILIATETYPE.AFFILIATETYPENAME AS label
    FROM    AFF_AFFILIATETYPE
    WHERE   AFF_AFFILIATETYPE.ISACTIVE  = 1
    AND     AFF_AFFILIATETYPE.ISDELETED = 0;

    SELECT  
            AFF_POLICYCOMMISION_TYPE.POLICYCOMMISIONTYPEID AS value,
            AFF_POLICYCOMMISION_TYPE.POLICYCOMMISIONTYPENAME AS label
    FROM    AFF_POLICYCOMMISION_TYPE
    WHERE   AFF_POLICYCOMMISION_TYPE.ISDELETED = 0
    AND     AFF_POLICYCOMMISION_TYPE.ISACTIVE = 1;

END