CREATE PROCEDURE CRM_ACCOUNT_Update_FromAff_AdminWeb
    @AFFILIATEREQUESTID BIGINT = 0,
    @MEMBERID BIGINT = 0,
    @UPDATEDUSER VARCHAR(20) = NULL
AS 
BEGIN

    DECLARE @PHONENUMBER VARCHAR(20) = NULL,
            @PROVINCEID BIGINT = 0,
            @DISTRICTID BIGINT = 0,
            @WARDID BIGINT = 0,
            @ADDRESS NVARCHAR(200) = NULL,
            @IDCARD VARCHAR(20) = NULL,
            @IDCARDDATE DATETIME = NULL,
            @IDCARDPLACE NVARCHAR(200) = NULL,
            @IDCARDFRONTSIDE VARCHAR(500) = NULL,
            @IDCARDBACKSIDE VARCHAR(500) = NULL,
            @LIVEIMAGE VARCHAR(500) = NULL;

    SELECT 
            @PHONENUMBER = PHONENUMBER,
            @PROVINCEID = PROVINCEID,
            @DISTRICTID = DISTRICTID,
            @WARDID = WARDID,
            @ADDRESS = ADDRESS,
            @IDCARD = IDCARD,
            @IDCARDDATE = IDCARDDATE,
            @IDCARDPLACE = IDCARDPLACE,
            @LIVEIMAGE = LIVEIMAGE,
            @IDCARDBACKSIDE = IDCARDBACKSIDE,
            @IDCARDFRONTSIDE = IDCARDFRONTSIDE
    FROM    AFF_AFFILIATEREQUEST
    WHERE   AFFILIATEREQUESTID = @AFFILIATEREQUESTID
    AND     REQUESTSTATUS = 2;

    UPDATE  CRM_ACCOUNT
    SET     UPDATEDUSER = @UPDATEDUSER,
            UPDATEDDATE = GETDATE(),
            PHONENUMBER = @PHONENUMBER,
            PROVINCEID = @PROVINCEID,
            DISTRICTID = @DISTRICTID,
            WARDID = @WARDID,
            ADDRESS = @ADDRESS,
            IDCARD = @IDCARD,
            IDCARDDATE = @IDCARDDATE,
            IDCARDPLACE = @IDCARDPLACE,
            LIVEIMAGE = @LIVEIMAGE,
            IDCARDBACKSIDE = @IDCARDBACKSIDE,
            IDCARDFRONTSIDE = @IDCARDFRONTSIDE
    WHERE   MEMBERID = @MEMBERID

END