CREATE PROCEDURE FOR_INTERPRET_GetListSpecial_AdminWeb
AS
BEGIN

    --LAY DANH SACH LUAN GIAI DAC BIET
    SELECT 
            INTERPRETID,
            BRIEFDESCRIPTION,
            [DESCRIPTION],
            ISCONDITIONOR,
            ISINTERPRETSPECIAL,
            ORDERINDEX
    FROM    FOR_INTERPRET
    WHERE   FOR_INTERPRET.ISACTIVE = 1
    AND     FOR_INTERPRET.ISDELETED = 0
    AND     FOR_INTERPRET.ISINTERPRETSPECIAL = 1
    ORDER BY ORDERINDEX;


    --LAY DANH SACH LUAN GIAI CON
    SELECT 
            FOR_INTERPRETDETAIL.INTERPRETID,
            FOR_INTERPRETDETAIL.INTERPRETDETAILID,
            FOR_INTERPRETDETAIL.INTERPRETDETAILNAME,
            FOR_INTERPRETDETAIL.FULLCONTENT,
            FOR_INTERPRETDETAIL.SHORTCONTENT,
            FOR_INTERPRETDETAIL.ORDERINDEX
    FROM    FOR_INTERPRETDETAIL
    WHERE   FOR_INTERPRETDETAIL.ISACTIVE = 1
    AND     FOR_INTERPRETDETAIL.ISDELETED = 0
    AND     EXISTS (
                        SELECT  1 
                        FROM    FOR_INTERPRET
                        WHERE   FOR_INTERPRETDETAIL.INTERPRETID = FOR_INTERPRET.INTERPRETID
                        AND     FOR_INTERPRET.ISACTIVE = 1
                        AND     FOR_INTERPRET.ISDELETED = 0
                        AND     FOR_INTERPRET.ISINTERPRETSPECIAL = 1
                    )

    --LAY DANH SACH THUOC TINH
    SELECT 
            FOR_INTERPRET_ATTRIBUTE.INTERPRETID,
            FOR_INTERPRET_ATTRIBUTE.INTERPRETATTRIBUTEID,
            FOR_INTERPRET_ATTRIBUTE.ATTRIBUTEID,
            FOR_INTERPRET_ATTRIBUTE.MAINNUMBER,
            FOR_INTERPRET_ATTRIBUTE.MAINNUMBERID,
            FOR_ATTRIBUTES.ATTRIBUTENAME

    FROM    FOR_INTERPRET_ATTRIBUTE

    JOIN    FOR_ATTRIBUTES
    ON      FOR_ATTRIBUTES.ATTRIBUTEID = FOR_INTERPRET_ATTRIBUTE.ATTRIBUTEID
    AND     FOR_ATTRIBUTES.ISACTIVE = 1
    AND     FOR_ATTRIBUTES.ISDELETED = 0

    WHERE   FOR_INTERPRET_ATTRIBUTE.ISDELETED = 0
    AND     FOR_INTERPRET_ATTRIBUTE.ISACTIVE = 1
    AND     EXISTS 
            (
                SELECT  1 
                FROM    FOR_INTERPRET
                WHERE   FOR_INTERPRET_ATTRIBUTE.INTERPRETID = FOR_INTERPRET.INTERPRETID
                AND     FOR_INTERPRET.ISACTIVE = 1
                AND     FOR_INTERPRET.ISDELETED = 0
                AND     FOR_INTERPRET.ISINTERPRETSPECIAL = 1

            )

END



