SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<locnd>
-- Create date: <09/09/2021>
-- Description:	<Chi tiết >
-- =============================================
ALTER PROCEDURE [dbo].[FOR_FORMULAINGREDIENTS_GetById_AdminWeb]
        @INGREDIENTID AS BIGINT  = NULL
AS
BEGIN
	SELECT 
            INGREDIENTID,
            INGREDIENTNAME,
            ISAPPLYDOB,
            PARAMDOBID,
            ISAPPLYNAME,
            PARAMNAMEID,
            CALCULATIONID,
            ORTHERINGREDIENTID1,
            ORTHERINGREDIENTID2,
            ISACTIVE,
            ISVOWELS,
            ISGENDER,
            DESCRIPTION,
            ISONLYFIRSTVOWEL,
            ISCONSONANT,
            ISFIRSTLETTER,
            ISLASTLETTER,
            ISNUMSHOW3TIME,
            ISNUMSHOW0TIME,
            ISTOTALSHORTENED,
            ISTOTALNOSHORTENED ,
            ISTOTAL2DIGIT,
            ISCURRENTAGE,
            ISCURRENTYEAR,
            VALUEINGREDIENTS,
            ISVALUEINGREDIENTS,
            GETLAST2DIGITS,
            ISCOUNTOFNUM,
            ISNUMLETTERS2DIGIT,
            ISNUMLETTERS1DIGIT,
            ISNUMLETTERNOSHORTENED,
            ISTOTALVALUES2DIGIT,
            ISTOTALVALUES1DIGIT,
            ISTOTALVALUENOSHORTENED,
            ISTOTALFIRSTLETTER2DIGIT,
            ISTOTALFIRSTLETTER1DIGIT,
            ISTOTALFIRSTLETTERNOSHORTENED,
            ISTOTALLETTERS2DIGIT,
            ISTOTALLETTERS1DIGIT,
            ISTOTALLETTERSNOSHORTENED,
            ISAPPLYOTHER,
            PARAMOTHERID,
            ISYEARVIEWING

	FROM    FOR_FORMULAINGREDIENTS 
    WHERE   ISDELETED = 0 
    AND     INGREDIENTID = @INGREDIENTID
END
GO
