SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<locnd>
-- Create date: <16/09/2021>
-- Description:	<danh sách thành phần>
-- =============================================
ALTER PROCEDURE [dbo].[FOR_FORMULAINGREDIENTS_GetList_AdminWeb]
			@KEYWORD nvarchar(1000) = NULL,
			@CREATEDDATEFROM nvarchar(10) = NULL, 
			@CREATEDDATETO nvarchar(10) = NULL,
			@PAGESIZE INT = 10,
			@PAGEINDEX INT = 1,
			@ISTYPE INT = null,
			@ISACTIVE INT = null,
			@ISAPPLYDOB INT = null,
			@ISAPPLYNAME INT = null,
            @ISAPPLYOTHER BIT = NULL
AS
BEGIN
			IF @KEYWORD ='' SET @KEYWORD = NULL
			declare @dFROM datetime = null, @dTO datetime = null
			if isnull(@CREATEDDATEFROM,'') <> '' set @dFROM = try_convert(datetime,@CREATEDDATEFROM,103)
			if isnull(@CREATEDDATETO,'') <> '' set @dTO = try_convert(datetime,@CREATEDDATETO,103)
-- 			IF @ISTYPE =2 SET @ISACTIVE = NULL 
			IF @ISACTIVE =2 SET @ISACTIVE = NULL 
			IF @ISTYPE =0 SET @ISAPPLYNAME = 1 
			IF @ISTYPE =1 SET @ISAPPLYDOB = 1
            IF @ISTYPE = 3 SET @ISAPPLYOTHER = 1

			SELECT 
			FOR_FORMULAINGREDIENTS.INGREDIENTID,
			FOR_FORMULAINGREDIENTS.INGREDIENTNAME,
			FOR_FORMULAINGREDIENTS.ISAPPLYDOB,
			FOR_FORMULAINGREDIENTS.ISAPPLYNAME,
			FOR_FORMULAINGREDIENTS.ISACTIVE,
			count(1) over() as TOTALITEMS,
-- 			CONVERT(DateTime, FOR_FORMULAINGREDIENTS.CREATEDDATE,103)CREATEDDATE
			convert(nvarchar(10),FOR_FORMULAINGREDIENTS.CREATEDDATE,103) CREATEDDATE,
            FOR_FORMULAINGREDIENTS.ISAPPLYOTHER,
            FOR_FORMULAINGREDIENTS.PARAMOTHERID
			FROM
			FOR_FORMULAINGREDIENTS
-- 			 JOIN FOR_FORMULAINGREDIENTS ON FOR_INTERPRET.ATTRIBUTEID = FOR_ATTRIBUTES.ATTRIBUTEID AND (@KEYWORD IS NULL OR ( FOR_ATTRIBUTES.ATTRIBUTENAME like '%'+ LTRIM(RTRIM(@KEYWORD)+'%' )))
			WHERE FOR_FORMULAINGREDIENTS.ISDELETED = 0
			AND (@KEYWORD IS NULL OR ( FOR_FORMULAINGREDIENTS.INGREDIENTNAME like '%'+ LTRIM(RTRIM(@KEYWORD)+'%' )))
			AND(@ISACTIVE IS NULL OR FOR_FORMULAINGREDIENTS.ISACTIVE = @ISACTIVE )
			AND(@ISAPPLYNAME IS NULL OR FOR_FORMULAINGREDIENTS.ISAPPLYNAME = @ISAPPLYNAME )
			AND(@ISAPPLYDOB IS NULL OR FOR_FORMULAINGREDIENTS.ISAPPLYDOB = @ISAPPLYDOB )
            AND (@ISAPPLYOTHER IS NULL OR FOR_FORMULAINGREDIENTS.ISAPPLYOTHER = @ISAPPLYOTHER)
			AND	(@dFROM IS NULL OR FOR_FORMULAINGREDIENTS.CREATEDDATE >= @dFROM )
			AND (@dTO IS NULL OR FOR_FORMULAINGREDIENTS.CREATEDDATE <= @dTO +1)
			ORDER BY CONVERT(DateTime, FOR_FORMULAINGREDIENTS.CREATEDDATE,101)  DESC   
		OFFSET (@PAGEINDEX -1)* @PAGESIZE ROWS
		FETCH NEXT @PAGESIZE ROWS ONLY
-- 			OFFSET (@PAGEINDEX -1)* @PAGESIZE ROWS
-- 			FETCH NEXT @PAGESIZE ROWS ONLY
END
GO
