SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<minhhv>
-- Create date: <2021/01/10>
-- Description:	lay all thong tin page cua product
-- =============================================
ALTER PROCEDURE [dbo].[MD_PRODUCT_PAGE_GetData_AdminWeb]
    @PRODUCTID BIGINT = 40063
AS
BEGIN
        --DANH SACH PAGE CUA SAN PHAM
		SELECT 			
                    MD_PAGE.PAGEID,
                    MD_PAGE.PAGENAME,
                    MD_PRODUCT_PAGE.ORDERINDEXPAGE,
                    MD_PAGE.PAGETYPE
        FROM        MD_PRODUCT_PAGE
        JOIN        MD_PAGE
        ON          MD_PAGE.PAGEID = MD_PRODUCT_PAGE.PAGEID
        AND         MD_PAGE.ISACTIVE = 1
        AND         MD_PAGE.ISDELETED = 0
        WHERE       MD_PRODUCT_PAGE.ISACTIVE = 1
        AND         MD_PRODUCT_PAGE.ISDELETED = 0
        AND         MD_PRODUCT_PAGE.PRODUCTID = @PRODUCTID
		GROUP BY    MD_PAGE.PAGEID,
                    MD_PAGE.PAGENAME,
                    MD_PRODUCT_PAGE.ORDERINDEXPAGE,
                    MD_PAGE.PAGETYPE;


        --DANH SACH CHI SO CUA DANH SACH PAGE CUA SAN PHAM
        SELECT      
                    MD_PRODUCT_PAGE.PAGEID,
					MD_PRODUCT_PAGE.ATTRIBUTESGROUPID,
					--IIF(MD_PRODUCT_PAGE.ATTRIBUTESGROUPID = -1, N'LUẬN GIẢI ĐẶC BIỆT', FOR_ATTRIBUTESGROUP.GROUPNAME) GROUPNAME,
                    FOR_ATTRIBUTESGROUP.GROUPNAME,
					MD_PRODUCT_PAGE.ORDERINDEX

        FROM        MD_PRODUCT_PAGE

        JOIN        FOR_ATTRIBUTESGROUP
        ON          FOR_ATTRIBUTESGROUP.ATTRIBUTESGROUPID = MD_PRODUCT_PAGE.ATTRIBUTESGROUPID
        AND         FOR_ATTRIBUTESGROUP.ISDELETED = 0
        AND         FOR_ATTRIBUTESGROUP.ISACTIVE = 1

        WHERE       MD_PRODUCT_PAGE.ISACTIVE = 1
        AND         MD_PRODUCT_PAGE.ISDELETED = 0
        AND         MD_PRODUCT_PAGE.PRODUCTID = @PRODUCTID
        GROUP BY     MD_PRODUCT_PAGE.PAGEID,
					MD_PRODUCT_PAGE.ATTRIBUTESGROUPID,
					--IIF(MD_PRODUCT_PAGE.ATTRIBUTESGROUPID = -1, N'LUẬN GIẢI ĐẶC BIỆT', FOR_ATTRIBUTESGROUP.GROUPNAME),
                    FOR_ATTRIBUTESGROUP.GROUPNAME,
					MD_PRODUCT_PAGE.ORDERINDEX
        UNION

        SELECT      
                    MD_PRODUCT_PAGE.PAGEID,
					MD_PRODUCT_PAGE.ATTRIBUTESGROUPID,
					N'LUẬN GIẢI ĐẶC BIỆT' GROUPNAME,
					MD_PRODUCT_PAGE.ORDERINDEX
        FROM        MD_PRODUCT_PAGE
        WHERE       MD_PRODUCT_PAGE.ISACTIVE = 1
        AND         MD_PRODUCT_PAGE.ISDELETED = 0
        AND         MD_PRODUCT_PAGE.PRODUCTID = @PRODUCTID
        AND         MD_PRODUCT_PAGE.ATTRIBUTESGROUPID = -1
        AND         MD_PRODUCT_PAGE.ATTRIBUTEID = -1
        AND         MD_PRODUCT_PAGE.ISINTERPRETSPECIAL = 1
        GROUP BY    MD_PRODUCT_PAGE.PAGEID,
					MD_PRODUCT_PAGE.ATTRIBUTESGROUPID,
					MD_PRODUCT_PAGE.ORDERINDEX

        --DANH SACH LUAN GIAI CUA DS CHI SO CUA PAGE SAN PHAM
        SELECT 
                    MD_PRODUCT_PAGE.PRODUCTPAGEID,
					MD_PRODUCT_PAGE.PAGEID,
					MD_PRODUCT_PAGE.INTERPRETID,
					MD_PRODUCT_PAGE.INTERPRETDETAILID,
					MD_PRODUCT_PAGE.ATTRIBUTESGROUPID,
					MD_PRODUCT_PAGE.ATTRIBUTEID,
					FOR_ATTRIBUTES.ATTRIBUTENAME,
					FOR_INTERPRETDETAIL.INTERPRETDETAILNAME,
					MD_PRODUCT_PAGE.ORDERINDEXINTERPRET

        FROM        MD_PRODUCT_PAGE

        JOIN        FOR_INTERPRETDETAIL
        ON          FOR_INTERPRETDETAIL.INTERPRETDETAILID = MD_PRODUCT_PAGE.INTERPRETDETAILID
        AND         FOR_INTERPRETDETAIL.ISACTIVE = 1
        AND         FOR_INTERPRETDETAIL.ISDELETED = 0

        JOIN        FOR_ATTRIBUTES
        ON          FOR_ATTRIBUTES.ATTRIBUTEID = MD_PRODUCT_PAGE.ATTRIBUTEID
        AND         FOR_ATTRIBUTES.ISDELETED = 0
        AND         FOR_ATTRIBUTES.ISACTIVE = 1

        WHERE       MD_PRODUCT_PAGE.ISDELETED = 0
        AND         MD_PRODUCT_PAGE.ISACTIVE = 1
        AND         MD_PRODUCT_PAGE.PRODUCTID = @PRODUCTID

        ORDER BY    MD_PRODUCT_PAGE.ATTRIBUTEID ASC, 
                    MD_PRODUCT_PAGE.ORDERINDEXINTERPRET ASC;


        --DANH SACH ALL LUAN GIAI CON CUA DANH SACH CHI SO
        SELECT
                    FOR_INTERPRETDETAIL.INTERPRETDETAILID,
                    FOR_INTERPRETDETAIL.INTERPRETID,
                    FOR_ATTRIBUTES.ATTRIBUTESGROUPID,
                    FOR_ATTRIBUTES.ATTRIBUTEID,
                    FOR_ATTRIBUTES.ATTRIBUTENAME,
                    FOR_INTERPRETDETAIL.INTERPRETDETAILNAME

		FROM        FOR_INTERPRETDETAIL 

		JOIN        FOR_INTERPRET
        ON          FOR_INTERPRET.INTERPRETID = FOR_INTERPRETDETAIL.INTERPRETID
        AND         FOR_INTERPRET.ISACTIVE=1
        AND         FOR_INTERPRET.ISDELETED=0

        JOIN        FOR_ATTRIBUTES
        ON          FOR_ATTRIBUTES.ATTRIBUTEID= FOR_INTERPRET.ATTRIBUTEID
		AND         FOR_ATTRIBUTES.ISACTIVE=1
		AND         FOR_ATTRIBUTES.ISDELETED=0

		JOIN        FOR_ATTRIBUTESGROUP
        ON          FOR_ATTRIBUTESGROUP.ATTRIBUTESGROUPID=FOR_ATTRIBUTES.ATTRIBUTESGROUPID
        AND         FOR_ATTRIBUTESGROUP.ISACTIVE=1
        AND         FOR_ATTRIBUTESGROUP.ISDELETED=0

		WHERE       FOR_INTERPRETDETAIL.ISACTIVE = 1
        AND         FOR_INTERPRETDETAIL.ISDELETED = 0
        AND         EXISTS
                    (
                        SELECT 1
                        FROM    MD_PRODUCT_PAGE
                        WHERE   MD_PRODUCT_PAGE.ISACTIVE = 1
                        AND     MD_PRODUCT_PAGE.ISDELETED = 0
                        AND     MD_PRODUCT_PAGE.PRODUCTID = @PRODUCTID
                        AND     MD_PRODUCT_PAGE.ATTRIBUTESGROUPID = FOR_ATTRIBUTESGROUP.ATTRIBUTESGROUPID
                    )

        --DANH SACH LUAN GIAI DAC BIET NEU CO
        SELECT 
                MD_PRODUCT_PAGE.ATTRIBUTEID,
                MD_PRODUCT_PAGE.ATTRIBUTESGROUPID,
                MD_PRODUCT_PAGE.PAGEID,
                MD_PRODUCT_PAGE.PRODUCTID,
                MD_PRODUCT_PAGE.INTERPRETID,
                MD_PRODUCT_PAGE.INTERPRETDETAILID
        FROM    MD_PRODUCT_PAGE
        WHERE   MD_PRODUCT_PAGE.ISACTIVE = 1
        AND     MD_PRODUCT_PAGE.ISDELETED = 0
        AND     MD_PRODUCT_PAGE.ISINTERPRETSPECIAL = 1
        AND     MD_PRODUCT_PAGE.ATTRIBUTESGROUPID = - 1
        AND     MD_PRODUCT_PAGE.ATTRIBUTEID = -1

END
GO
