SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[MD_PRODUCT_GetById_AdminWeb]
    @PRODUCTID BIGINT = 0
AS
BEGIN

    --0. Chi tiet san pham
    SELECT 
                MD_PRODUCT.PRODUCTID,
                MD_PRODUCT.PRODUCTCATEGORYID,
                MD_PRODUCT.PRODUCTNAME,
                MD_PRODUCT.PRODUCTNAMESHOWWEB,
                MD_PRODUCT.URLPRODUCT,
                MD_PRODUCT.ISACTIVE,
                MD_PRODUCT.ISSHOWWEB,
                MD_PRODUCT.SHORTDESCRIPTION,
                MD_PRODUCT.PRODUCTCONTENTDETAIL,
                ISNULL(ISWEBVIEW, 0) ISWEBVIEW,
                ISNULL(ISSHOWMENU, 0) ISSHOWMENU,
                MD_PRODUCT.LINKLANDINGPAGE
    FROM        MD_PRODUCT
    WHERE       MD_PRODUCT.ISDELETED = 0
    AND         MD_PRODUCT.PRODUCTID = @PRODUCTID;

    --1. Hinh anh san pham
    SELECT   PRO_PRODUCTIMAGES.PRODUCTID,
             PRO_PRODUCTIMAGES.PICTUREURL,
             PRO_PRODUCTIMAGES.ISDEFAULT
    FROM     PRO_PRODUCTIMAGES
    WHERE    PRO_PRODUCTIMAGES.ISDELETED = 0
    AND      PRO_PRODUCTIMAGES.PRODUCTID = @PRODUCTID
    ORDER BY PRO_PRODUCTIMAGES.ISDEFAULT;


    --2. Chi so cua san pham
    SELECT  
					
                MD_PRODUCT_ATTRIBUTES.PRODUCTID,
                MD_PRODUCT_ATTRIBUTES.ATTRIBUTESGROUPID,
                MD_PRODUCT_ATTRIBUTES.ORDERINDEX
    FROM        MD_PRODUCT_ATTRIBUTES

    WHERE       MD_PRODUCT_ATTRIBUTES.ISDELETED = 0
    AND         MD_PRODUCT_ATTRIBUTES.PRODUCTID = @PRODUCTID
	GROUP BY	MD_PRODUCT_ATTRIBUTES.PRODUCTID,
                MD_PRODUCT_ATTRIBUTES.ATTRIBUTESGROUPID ,
                MD_PRODUCT_ATTRIBUTES.ORDERINDEX
    ORDER BY    MD_PRODUCT_ATTRIBUTES.ORDERINDEX

    --3. Danh sach luan giai cua san pham	
	SELECT  
				MD_PRODUCT_ATTRIBUTES.PROATTRIBUTESID,
                MD_PRODUCT_ATTRIBUTES.PRODUCTID,
                MD_PRODUCT_ATTRIBUTES.ATTRIBUTESGROUPID,
                MD_PRODUCT_ATTRIBUTES.INTERPRETID,
                MD_PRODUCT_ATTRIBUTES.INTERPRETDETAILID,
                MD_PRODUCT_ATTRIBUTES.ISSHOWSEARCHRESULT,
                MD_PRODUCT_ATTRIBUTES.TEXTURL,
                MD_PRODUCT_ATTRIBUTES.URL,
                FOR_INTERPRETDETAIL.INTERPRETDETAILNAME
    FROM        MD_PRODUCT_ATTRIBUTES
    
    LEFT JOIN   FOR_INTERPRETDETAIL
    ON          FOR_INTERPRETDETAIL.INTERPRETDETAILID = MD_PRODUCT_ATTRIBUTES.INTERPRETDETAILID
		
    AND         FOR_INTERPRETDETAIL.ISDELETED = 0
    AND         FOR_INTERPRETDETAIL.ISACTIVE = 1

    WHERE       MD_PRODUCT_ATTRIBUTES.ISDELETED = 0
    AND         MD_PRODUCT_ATTRIBUTES.PRODUCTID = @PRODUCTID
    ORDER BY    MD_PRODUCT_ATTRIBUTES.CREATEDDATE

		
END
GO
