SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[MD_PAGE_GetListPage_AdminWeb]
AS
BEGIN
	SELECT 
            PAGEID,
            PAGENAME,
            PAGETYPE
	FROM    MD_PAGE
	WHERE   ISDELETED=0
	AND     ISACTIVE =1
END
GO
