SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[MD_PRODUCT_Create_AdminWeb]
    @PRODUCTCATEGORYID BIGINT = 0,
    @PRODUCTNAME NVARCHAR(300) = NULL,
    @PRODUCTNAMESHOWWEB NVARCHAR(300) = NULL,
    @URLPRODUCT VARCHAR(500) = NULL,
    @SHORTDESCRIPTION NVARCHAR(1000) = NULL,
    @PRODUCTCONTENTDETAIL NVARCHAR(MAX) = NULL,
    @ISACTIVE BIT = 0,
    @ISSHOWWEB BIT = 0,
    @ISWEBVIEW BIT = 0,
    @ISSHOWMENU BIT = 0,
    @CREATEDUSER VARCHAR(200) = NULL,
    @LINKLANDINGPAGE NVARCHAR(1000) = NULL
AS
BEGIN
    DECLARE @PRODUCTCODE AS VARCHAR(50) = NULL
						
	SET @PRODUCTCODE = 'PRO' + CONVERT(VARCHAR(6), GETDATE(), 12) + 
					RIGHT('00000' + CAST((SELECT COUNT(1) + 1 FROM MD_PRODUCT) AS VARCHAR(100)),5)
		

    INSERT INTO MD_PRODUCT
    (
        PRODUCTCATEGORYID,
        PRODUCTCODE,
        PRODUCTNAME,
        PRODUCTNAMESHOWWEB,
        URLPRODUCT,
        PRODUCTCONTENTDETAIL,
        SHORTDESCRIPTION,
        ISSHOWWEB,
        ISACTIVE,
        ISDELETED,
        CREATEDDATE,
        CREATEDUSER,
        ISWEBVIEW,
        ISSHOWMENU,
        LINKLANDINGPAGE
    )
    VALUES
    (
        @PRODUCTCATEGORYID,
        @PRODUCTCODE,
        @PRODUCTNAME,
        @PRODUCTNAMESHOWWEB,
        @URLPRODUCT,
        @PRODUCTCONTENTDETAIL,
        @SHORTDESCRIPTION,
        @ISSHOWWEB,
        @ISACTIVE,
        0,
        GETDATE(),
        @CREATEDUSER,
        @ISWEBVIEW,
        @ISSHOWMENU,
        @LINKLANDINGPAGE
    )

    SELECT SCOPE_IDENTITY() AS product_id

END
GO
