SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[MD_PRODUCT_Update_AdminWeb]
    @PRODUCTID BIGINT = 0,
    @PRODUCTCATEGORYID BIGINT = 0,
    @PRODUCTNAME NVARCHAR(300) = NULL,
    @PRODUCTNAMESHOWWEB NVARCHAR(300) = NULL,
    @URLPRODUCT VARCHAR(500) = NULL,
    @SHORTDESCRIPTION NVARCHAR(1000) = NULL,
    @PRODUCTCONTENTDETAIL NVARCHAR(MAX) = NULL,
    @ISACTIVE BIT = 0,
    @ISSHOWWEB BIT = 0,
    @ISWEBVIEW BIT = 0,
    @ISSHOWMENU BIT = 0,
    @UPDATEDUSER VARCHAR(200) = NULL,
    @LINKLANDINGPAGE NVARCHAR(1000) = NULL
AS
BEGIN
   
    UPDATE  MD_PRODUCT
    SET     PRODUCTCATEGORYID = @PRODUCTCATEGORYID,
            PRODUCTNAME = @PRODUCTNAME,
            PRODUCTNAMESHOWWEB = @PRODUCTNAMESHOWWEB,
            URLPRODUCT = @URLPRODUCT,
            PRODUCTCONTENTDETAIL = @PRODUCTCONTENTDETAIL,
            SHORTDESCRIPTION = @SHORTDESCRIPTION,
            ISSHOWWEB = @ISSHOWWEB,
            ISACTIVE = @ISACTIVE,
            UPDATEDDATE = GETDATE(),
            UPDATEDUSER = @UPDATEDUSER,
            ISWEBVIEW = @ISWEBVIEW,
            ISSHOWMENU = @ISSHOWMENU,
            LINKLANDINGPAGE = @LINKLANDINGPAGE
    WHERE   PRODUCTID = @PRODUCTID
    
    SELECT @@ROWCOUNT as result
END
GO
