SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<locnd>
-- Create date: <14/09/2021>
-- Description:	<danh sách đơn hàng>
-- =============================================
ALTER PROCEDURE [dbo].[SL_ORDER_GetList_AdminWeb_Backup]
			@KEYWORD nvarchar(1000) = NULL,
			@CREATEDDATEFROM nvarchar(10) = NULL, 
			@CREATEDDATETO nvarchar(10) = NULL,
			@PAGESIZE INT = 10,
			@PAGEINDEX INT = 1,
			@ISDELETED INT = null,
			@STATUS INT = null
AS
BEGIN
			IF @KEYWORD ='' SET @KEYWORD = NULL
			declare @dFROM datetime = null, @dTO datetime = null
			if isnull(@CREATEDDATEFROM,'') <> '' set @dFROM = try_convert(datetime,@CREATEDDATEFROM,103)
			if isnull(@CREATEDDATETO,'') <> '' set @dTO = try_convert(datetime,@CREATEDDATETO,103)
			IF @STATUS =2 SET @STATUS = NULL
			IF @ISDELETED =2 SET @ISDELETED = NULL
			SELECT 
			SL_ORDER.ORDERID,
			SL_ORDER.ORDERNO,
				 (SUBSTRING(( SELECT '; '+ CONVERT(nVarchar(2000),MD_PRODUCT.PRODUCTNAME ,0)
			FROM dbo.MD_PRODUCT
			LEFT JOIN dbo.SL_ORDERDETAIL on MD_PRODUCT.PRODUCTID = SL_ORDERDETAIL.PRODUCTID AND MD_PRODUCT.ISDELETED = 0
			WHERE SL_ORDERDETAIL.ORDERID = SL_ORDER.ORDERID
			FOR XML PATH ('')), 2, 100))  PRODUCTNAME,
			convert(nvarchar(10),SL_ORDER.ORDERDATE,103) ORDERDATE,
			SL_ORDER.SUBTOTAL,
			SL_ORDER.STATUS,
			CRM_ACCOUNT.FULLNAME,
			CRM_ACCOUNT.PHONENUMBER,
			convert(nvarchar(10),SL_ORDER.CREATEDDATE,103) CREATEDDATE,
			PRO_COMBOS.COMBONAME,
            SL_ORDER.ORDERTYPE
			FROM
			SL_ORDER
			left JOIN CRM_ACCOUNT ON CRM_ACCOUNT.MEMBERID = SL_ORDER.MEMBERID  
			left JOIN SL_ORDERDETAIL ON SL_ORDERDETAIL.ORDERID = SL_ORDER.ORDERID
			left JOIN MD_PRODUCT ON SL_ORDERDETAIL.PRODUCTID = MD_PRODUCT.PRODUCTID 
			left JOIN PRO_COMBOS ON SL_ORDERDETAIL.COMBOID = PRO_COMBOS.COMBOID 
			WHERE 
-- 			SL_ORDER.ISDELETED=0
				(@ISDELETED IS NULL OR SL_ORDER.ISDELETED = @ISDELETED)
			 AND (@KEYWORD IS NULL OR ( SL_ORDER.ORDERNO like '%'+ LTRIM(RTRIM(@KEYWORD)+'%' ))or (@KEYWORD IS NULL OR ( CRM_ACCOUNT.FULLNAME like '%'+ LTRIM(RTRIM(@KEYWORD)+'%' ))or (@KEYWORD IS NULL OR ( MD_PRODUCT.PRODUCTNAME like '%'+ LTRIM(RTRIM(@KEYWORD)+'%' )))or (@KEYWORD IS NULL OR ( PRO_COMBOS.COMBONAME like '%'+ LTRIM(RTRIM(@KEYWORD)+'%' ))) ))
			AND(@STATUS IS NULL OR SL_ORDER.STATUS = @STATUS )
			AND	(@dFROM IS NULL OR SL_ORDER.CREATEDDATE >= @dFROM )
			AND (@dTO IS NULL OR SL_ORDER.CREATEDDATE <= @dTO +1)
GROUP BY SL_ORDER.ORDERID,
			SL_ORDER.ORDERNO,
			 SL_ORDER.ORDERDATE,
			SL_ORDER.SUBTOTAL,
			SL_ORDER.STATUS,
			CRM_ACCOUNT.FULLNAME,
			CRM_ACCOUNT.PHONENUMBER,
			PRO_COMBOS.COMBONAME,
			SL_ORDER.CREATEDDATE,
            SL_ORDER.ORDERTYPE

			ORDER BY CONVERT(DateTime, SL_ORDER.CREATEDDATE,101)  DESC
			OFFSET (@PAGEINDEX -1)* @PAGESIZE ROWS
			FETCH NEXT @PAGESIZE ROWS ONLY
END
GO
